### ISSUE TITLE
Please loosen bleak pin to >=0.21.0

### ISSUE THREAD

**Issue by bdraco** [EuleMitKeule/eq3btsmart#2]
https://github.com/EuleMitKeule/eq3btsmart/blob/c931565335ef723a3f7e9f897c231fd89b145e24/pyproject.toml#L14

This library is blocking HA from upgrading bleak

https://github.com/home-assistant/core/pull/116955

**Comment by EuleMitKeule** [comment]
Done ✅ 

Please let me know if there are other dependency pins which might lead to problems in the future.
Also I guess the dependency has to be updated to the new release `1.1.7` in [`core`](https://github.com/home-assistant/core) now?

**Comment by bdraco** [comment]
It looks like construct and construct-typing eventually will be an issue as well https://github.com/EuleMitKeule/eq3btsmart/blob/8b639376a50f8a4ca64dd1b43826a62b72e0bf79/pyproject.toml#L15

pytest-asyncio looks like it made it into deps instead of `tool.poetry.group.test.dependencies` https://github.com/EuleMitKeule/eq3btsmart/blob/8b639376a50f8a4ca64dd1b43826a62b72e0bf79/pyproject.toml#L17

**Comment by bdraco** [comment]
> Also I guess the dependency has to be updated to the new release `1.1.7` in [`core`](https://github.com/home-assistant/core) now?

Yes, once we have it updated, I'll be able to complete the bleak update

**Comment by bdraco** [comment]
Thanks!

**Comment by EuleMitKeule** [comment]
> It looks like construct and construct-typing eventually will be an issue as well 

Should they be changed to eg. `>=2.10.68`?

**Comment by bdraco** [comment]
Yes

**Comment by EuleMitKeule** [comment]
Done ✅ 

Should I create the PR to update `core`'s `eq3btsmart` dependency to `1.1.8` or will you do it?

**Comment by bdraco** [comment]
Its always better if the codeowner does their own dep bump PRs, but I'm happy to do it as well if you want.

**Comment by EuleMitKeule** [comment]
No problem, I'm gonna do it right now 👍

**Comment by EuleMitKeule** [comment]
PR can be found [here](https://github.com/home-assistant/core/pull/117051).
