### ISSUE TITLE
battery level

### ISSUE THREAD

**Issue by dxdx65** [EuleMitKeule/eq3btsmart#4]
Hi, is it possible to include as attribute of the climate entity the battery level indicator of the thermostat, as it was in the old EQ-3 integration? It can help a lot to prevent out of service due to the empty batteries.. thanks a lot

**Comment by EuleMitKeule** [comment]
Hi, I will try to add the missing features to the core integration in the coming weeks. Issues regarding the core integration should be opened in the Home Assistant core repository.
